# Generated by Django 3.2.9 on 2021-11-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tattooparlor',
            unique_together={('cvr', 'supplier_cvr')},
        ),
        migrations.AlterModelTable(
            name='tattooparlor',
            table='tattooparlor',
        ),
    ]
