# Generated by Django 3.2.9 on 2021-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211117_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='artiststats',
            fields=[
                ('Name', models.CharField(max_length=75, primary_key=True, serialize=False, unique=True)),
                ('CustommerCount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artiststats',
                'managed': False,
            },
        ),
    ]
